### ISSUE TITLE
Seduce and Divine Shield

### ISSUE THREAD

**Issue by fizbump** [TeamEverlook/Everlook-BugTracker#313] opened 2024-01-13 16:55 UTC
**Describe the bug**
The warlock succubus ability "Seduction" can land through a paladin's Divine Shield ("bubble"), which should make you immune to it.

**To Reproduce**
1. Cast Divine Shield as a paladin
2. Have a warlock cast "Seduction" with their succubus pet
3. You become CC'ed

**Expected behavior**
Paladin's Divine Shield should protect you from all spells while it is up. Seduction is a spell and thus, should not be able to affect a paladin who has Divine Shield up.

**Screenshots**
https://pasteboard.co/x3rwsWklFWRm.png

**Comment by NiDiCi** [comment] 2024-01-16 14:35
Me and nothing tested this and cannot reproduce the bug.

Tested this by first
1. Casting Divine shield as a paladin
2. Have a warlock cast "Seduction" with their succubus pet

Despite testing this around 30 times no CC was applied as expected. We also tried the other way around and found that the exspected behavior still happens.

1. Have a warlock cast "Seduction" with their succubus pet
2. Casting Divine shield as a paladin

Still worked as intended. Also tried a few times to time the casting at the same time but could not get the bug to happen.

**Comment by NiDiCi** [comment] 2024-01-17 16:35
Tried again today but I'm still unsuccessful in reproducing the problem, my guess is that it's skill batching problem. If it's possible for you to get a video of it happening, or a detailed way of reproducing the problem please send it in again but for now I will close this issue.

**Closed as not planned by NiDiCi** 2024-01-17 16:35 UTC
Labels: Need Info, Need QA
