### ISSUE TITLE
Prison Break In despawn of stones. 

### ISSUE THREAD

**Issue by Buggiboi** [TeamEverlook/Everlook-BugTracker#174] opened 2023-04-06 08:54 UTC
[Prison break in despawn.docx](https://github.com/TeamEverlook/Everlook-BugTracker/files/11168239/Prison.break.in.despawn.docx)
Here is proof I killed the last boss. Also I never turned it in, never got credit and have none of the stones in my bag despite killing all of them. Hearthed back to make sure and still could't see the quest, pick it up or turn it in. My bags are clearly empty of all stones despite just killing last one in tower.\

**Comment by NiDiCi** [comment] 2024-01-22 06:24
Hi Buggiboi,

To start of I hope your issue has been resolve. I've read through what you've written and looked through the screenshots. The mob in the first screenshot is for the quest [Prison break in](https://www.wowhead.com/classic/quest=544/prison-break-in) but you don't show that quest in the second screenshot where you show of your quests. In the second screenshot you show the quest [Dangerous!](https://www.wowhead.com/classic/quest=567/dangerous) you are missing the kill on Miner Hackett whos down in the azurelode mine, but this has nothing to do with Kegan Darkmar. I'm going to close this issue, please make a new bug report again with what the issue is and how to clearly reproduce it.

**Closed as completed by NiDiCi** 2024-01-22 06:24 UTC
Labels: NOT A BUG
