### ISSUE TITLE
DME Mining/Herb

### ISSUE THREAD

**Issue by Zackor2** [TeamEverlook/Everlook-BugTracker#11] opened 2022-12-16 22:36 UTC
**Describe the bug**
Mining: DME Mining nodes at end if boss not killed 1/2 able to mine. Will this stay this way or changed some day to either mine all or none depending on boss kill?

Herb: Dreamfoil respawned (near first rock jump) after clear/died/ran back to mine at end (healer was herb).
**To Reproduce**
5. 
GM Torvon checked and confirmed 1 node not able to mine unless boss killed. 

**Expected behavior**
Pro and cons to mineable or not. Just was confused at "failed" mining when other node was able to mine.
Herb should not respawn in dung.

**Screenshots**

**Additional context**

**Comment by Neto-WoW** [comment] 2022-12-18 03:23
Sorry - I dont see the bug here. Could you clarify?

**Comment by Zackor2** [comment] 2022-12-18 08:05
Herbs respawning in dung, and if the RTV nodes should be locked to boss kill or not. Torvon told me to make a post just to double check. I'm cool with either way just making sure its as intended.

**Comment by NiDiCi** [comment] 2024-01-18 00:35
The part about herbing I can't reproduce and might have been fixed.

Tested this today and the issue with one rich thorium vein being tied to the boss is still there. Since this post is quite unclear and there is no steps on how to reproduce the problem I will close this issue and open a new one to make things clearer to the devs.

**Closed by NiDiCi** 2024-01-18 00:35 UTC
Labels: Low Priority
