### ISSUE TITLE
 Fraud, purify the game environment, and ask GM for help

### ISSUE THREAD

**Issue by zxj19891112** [TeamEverlook/Everlook-BugTracker#112] opened 2023-02-02 18:28 UTC
Just now, I went to the mailbox to collect the mail, but didn’t pay attention to the other party’s name. I clicked the email attachment, and the gold coin was defrauded.

The fraudster’s name: letteri

Fake the auction house to send the successful auction email to the player to defraud the player of gold coins. Please GM to deal with this behavior.

Please check with the administrator and reply to the gold coin if you can.  a player who sincerely loves World of Warcraft, Xmmoui.Thank you very much,

![微信图片_20230202222329](https://user-images.githubusercontent.com/124260483/216414962-064570a0-249b-4d82-99a0-29e85b220a49.jpg)

Looking forward to receiving the reply from the administrator.

Email:61175609@qq.com

**Comment by Godmatik** [comment] 2023-02-06 01:47
next time pay attention

**Comment by NiDiCi** [comment] 2024-01-22 07:08
Hi zxj19891112,

I hope this has already been resolved by a GM but this is not a bug. I'm not sure how this is handled by the gms but if you encounter this again please make a ticket on the discord.

**Closed as completed by NiDiCi** 2024-01-22 07:08 UTC
Labels: GM Issue
